language: node_js

node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
 
# Install Haxe before running the test.
before_install:
  - sudo apt-get update                                # run update before installing anything
  - sudo apt-get install python-software-properties -y # for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y      # add the ubuntu ppa that contains haxe
  - sudo apt-get update                                # pull info from ppa

install:
  - sudo apt-get install haxe -y                       # install haxe (and neko)
 
script:
  - make test
  - make php   # make sure other languages at least generate
  - make java
  - make py
  - make cs
